api-version: "1.13"
author: "Thiago 'Coder' Silva"
commands:
  am:
    description: "Reloads automessages config, and reloads plugin"
main: "br.com.thiagocodero.automessages.AutoMessages"
name: "AutoMessages"
version: "1.0.3"